### ISSUE TITLE
Filtered images for sevae training

### ISSUE THREAD

**Issue by guglielmo610** [ntnu-arl/sevae#2]
Hello,
can you please share how to obtain the filtered images required for the training of the model?
In particular, I've collect some data (depth images + segmentation images) from gym simulator and I already serialized this data into some TFRecord files. The problem is that apparently the training is expecting not just the depth images and the segmentation images, but also some filtered images. How can I obtain that?
Thank you in advance

**Comment by HuanNguyenARL** [comment]
@mihirk284 can you have a look at this?

**Comment by mihirk284** [comment]
Hei @guglielmo610 , 

Filtered image was a thing we were trying out before this work, but we do not use it anymore. We kept it in code to maintain compatibility with our setup. 


You can fill in this image with black pixels and ignore it, otherwise, you can just write a custom tfrecord feature descriptor [here](https://github.com/ntnu-arl/sevae/blob/f7c6e680860e679f3f72ef07f9cb30540c302b26/sevae/datasets/depth_semantic_image_dataset.py#L34) based on your .tfrecord file setup.


Alternatively, you can just set the value returned to a torch image with all black pixels [here](https://github.com/ntnu-arl/sevae/blob/f7c6e680860e679f3f72ef07f9cb30540c302b26/sevae/datasets/depth_semantic_image_dataset.py#L56). This is not used in the training process, but this is the easiest way to get it to work for now.

**Comment by guglielmo610** [comment]
Thank you
